<a href="https://colab.research.google.com/github/sowmyarshetty/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition','Department']]


In [4]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Age','Education','DistanceFromHome','JobSatisfaction','OverTime','StockOptionLevel','WorkLifeBalance','YearsAtCompany','YearsSinceLastPromotion','NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


# Show the data types for X_df
X_df.dtypes


Age                         int64
Education                   int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [5]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
X_df['OverTime'].value_counts()
X_df['OverTime'] = X_df['OverTime'].replace({'Yes':1,'No':0})
X_df['OverTime'].value_counts()



<ipython-input-5-21050fb0a023>:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X_df['OverTime'] = X_df['OverTime'].replace({'Yes':1,'No':0})
<ipython-input-5-21050fb0a023>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_df['OverTime'] = X_df['OverTime'].replace({'Yes':1,'No':0})


OverTime
0    1054
1     416
Name: count, dtype: int64

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_df,y_df,random_state=42)


In [7]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_train_scaled = scaler.fit_transform(X_train)

# Scale the training and testing data
X_test_scaled = scaler.transform(X_test)


In [8]:
y_df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [9]:
y_df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [10]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
ohedept = OneHotEncoder(sparse_output=False)
# Fit the encoder to the training data
# Create two new variables by applying the encoder
# to the training and testing data

y_train_dept = y_train[["Department"]]
y_test_dept = y_test[["Department"]]


y_train_dept_encoded = ohedept.fit_transform(y_train_dept)
dept_column_names = ohedept.get_feature_names_out(['Department'])

y_test_dept_encoded = ohedept.transform(y_test_dept)

#y_train_dept_encoded



In [11]:
# Create a OneHotEncoder for the Attrition column
oheattr = OneHotEncoder(sparse_output=False)
y_train_attr = y_train[["Attrition"]]
y_test_attr = y_test[["Attrition"]]

# Fit the encoder to the training data
y_train_attr_encoded = oheattr.fit_transform(y_train_attr)
attr_column_names = oheattr.get_feature_names_out(['Attrition'])
y_test_attr_encoded = oheattr.transform(y_test_attr)


## Part 2: Create, Compile, and Train the Model

In [12]:
# Find the number of columns in the X training data.
input_shape = X_train_scaled.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(input_shape,),name="input_features")

# Create at least two shared layers
shared_layer1 = layers.Dense(64,activation='relu')(input_layer)
shared_layer2 = layers.Dense(32,activation='relu')(shared_layer1)



In [13]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
hidden_layer_dept = layers.Dense(16,activation='relu')(shared_layer2)

# Create the output layer
dept_output = layers.Dense(3, activation='softmax', name='dept_output')(hidden_layer_dept)



In [14]:
# Create a branch for Attrition
# with a hidden layer and an output layer
hidden_layer_attr = layers.Dense(16,activation='relu')(shared_layer2)

# Create the hidden layer
attr_output = layers.Dense(2, activation='sigmoid', name='attr_output')(hidden_layer_attr)

# Create the output layer


In [15]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output, attr_output])

# Compile the model
model.compile(optimizer="adam", loss={"dept_output" : "categorical_crossentropy",
                                      "attr_output" : "binary_crossentropy"},
              metrics={"dept_output" : "accuracy",
                       "attr_output" : "accuracy"})



# Summarize the model

model.summary()


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_features            │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            704 │ input_features[0][0]   │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 32)             │          2,080 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_2 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_3 (Dense)           │ (None, 16)             │            528 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dept_output (Dense)       │ (None, 3)              │             51 │ dense_2[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attr_output (Dense)       │ (None, 2)              │             34 │ dense_3[0][0]          │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 3,925 (15.33 KB)

 Trainable params: 3,925 (15.33 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Train the model
# Fit the model
model.fit(X_train_scaled, {"dept_output" : y_train_dept_encoded, "attr_output" : y_train_attr_encoded},
          epochs=10,
          batch_size=32,
          validation_split=0.2)

Epoch 1/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 12s 90ms/step - attr_output_accuracy: 0.6563 - attr_output_loss: 0.6608 - dept_output_accuracy: 0.2277 - dept_output_loss: 1.1704 - loss: 1.8315 - val_attr_output_accuracy: 0.7873 - val_attr_output_loss: 0.5856 - val_dept_output_accuracy: 0.5385 - val_dept_output_loss: 0.9680 - val_loss: 1.5542
Epoch 2/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attr_output_accuracy: 0.8503 - attr_output_loss: 0.5287 - dept_output_accuracy: 0.6495 - dept_output_loss: 0.9150 - loss: 1.4440 - val_attr_output_accuracy: 0.7873 - val_attr_output_loss: 0.5196 - val_dept_output_accuracy: 0.6063 - val_dept_output_loss: 0.8395 - val_loss: 1.3610
Epoch 3/10
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attr_output_accuracy: 0.8263 - attr_output_loss: 0.4734 - dept_output_accuracy: 0.6628 - dept_output_loss: 0.7814 - loss: 1.2550 - val_attr_output_accuracy: 0.7873 - val_attr_output_loss: 0.4978 - val_dept_output_accuracy: 0.6063 - val_dept_output_loss: 0.8202 - val_loss: 1.3208
Ep

In [17]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'dept_output': y_test_dept_encoded, 'attr_output': y_test_attr_encoded})

print(f"Total Loss: {test_results[0]:.4f}")
print(f"Department Loss: {test_results[1]:.4f}")
print(f"Attrition Loss: {test_results[2]:.4f}")


12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attr_output_accuracy: 0.8593 - attr_output_loss: 0.3732 - dept_output_accuracy: 0.6477 - dept_output_loss: 0.8126 - loss: 1.1839 
Total Loss: 1.1586
Department Loss: 0.8187
Attrition Loss: 0.3527


In [18]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {test_results[3]:.4f}")
print(f"Attrition Accuracy: {test_results[4]:.4f}")


Department Accuracy: 0.8723
Attrition Accuracy: 0.6522


In [19]:
y_test_dept_pred ,y_test_attr_pred = model.predict(X_test_scaled)
print(y_test_dept_pred)
from sklearn.metrics import roc_auc_score,confusion_matrix, classification_report, balanced_accuracy_score
print(f"roc_auc_score dept {roc_auc_score(y_test_dept_encoded, y_test_dept_pred)}")

print(f"roc_auc_score attr {roc_auc_score(y_test_attr_encoded, y_test_attr_pred)}")

12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step
[[0.02086207 0.6954203  0.28371757]
 [0.03098818 0.7485528  0.22045894]
 [0.02022464 0.5909048  0.38887066]
 ...
 [0.02994899 0.7099916  0.2600595 ]
 [0.03944206 0.6944968  0.26606116]
 [0.09308878 0.58579993 0.32111138]]
roc_auc_score dept 0.5104338695999306
roc_auc_score attr 0.72822265625


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Since our attrition dataset is imbalanced with few "yes" cases and far more "no"cases, accuracy may not give us the true picture.  Metrics like roc_auc_score will provide better understanding .Metrics like ROC-AUC can handle probabilities directly. For multi-class classification (department prediction), roc_auc_score can be useful

2. I chose softmax for department classification because department classification was mutually exclusive i.e. every employee could be part of only one department . I chose sigmoid for attrition which is suitable for binary classification.
3. The model can be improved by using heat map to identify the co-linear columns,  removing one of the co-linear feature columns, adjusting hyperparameters (adjusting batch size, epochs). Handling Class Imbalance using class weights, SMOTE (Synthetic Minority Over-sampling Technique)  or deeper neural network models by adding more dense layers with more neurons.